# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Pages Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      

    - name: Installing my packages
      run: npm ci

    - name: Build my App  
      run: npm run build
      env:
        NEXT_PUBLIC_BASE_PATH: ""
    - run: npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: ""
    - run: touch ./out/.nojekyll
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        BRANCH: build # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
        clean: true